webtalk_init -webtalk_dir C:/Users/Rutgers/OneDrive - Rutgers University/Desktop/Embedded Systems/Lab3/Lab3.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 26 23:26:00 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3286242" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "74d74d43-14e4-47a2-9b2e-0f40c145778c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c34334880bf142a481150ac250b6b2b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5700G with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "478836 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14184_KB" -context "xsim\\usage"
webtalk_transmit -clientid 605323249 -regid "" -xml C:/Users/Rutgers/OneDrive - Rutgers University/Desktop/Embedded Systems/Lab3/Lab3.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Rutgers/OneDrive - Rutgers University/Desktop/Embedded Systems/Lab3/Lab3.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Rutgers/OneDrive - Rutgers University/Desktop/Embedded Systems/Lab3/Lab3.sim/sim_1/behav/xsim/xsim.dir/uart_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
