#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Mar 27 18:36:19 EDT 2025
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto c34334880bf142a481150ac250b6b2b3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot uart_top_tb_behav xil_defaultlib.uart_top_tb -log elaborate.log"
xelab -wto c34334880bf142a481150ac250b6b2b3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot uart_top_tb_behav xil_defaultlib.uart_top_tb -log elaborate.log

