@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Mar 27 09:59:49 -0400 2025
REM SW Build 3286242 on Wed Jul 28 13:10:47 MDT 2021
REM
REM IP Build 3279568 on Wed Jul 28 16:48:48 MDT 2021
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto c34334880bf142a481150ac250b6b2b3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot uart_top_tb_behav xil_defaultlib.uart_top_tb -log elaborate.log"
call xelab  -wto c34334880bf142a481150ac250b6b2b3 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot uart_top_tb_behav xil_defaultlib.uart_top_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
